services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: herba-scan-dashboard-app
        container_name: herba-scan-dashboard-app
        restart: unless-stopped
        working_dir: /var/www
        env_file:
            - .env
        volumes:
            - appdata:/var/www/storage
        networks:
            - proxy
        ports:
            - "9000:9000"
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: herba-scan-dashboard-nginx
        restart: unless-stopped
        ports:
            - "8001:80"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - proxy
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: herba-scan-dashboard-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - proxy

networks:
    proxy:
        external: true

volumes:
    dbdata:
        driver: local
    appdata:
        driver: local
