services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: herba-scan-app
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    env_file:
      - .env.docker
    
    depends_on:
      - db
    networks:
      - proxy

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: herba-scan-dashboard-db
    environment:
      MYSQL_DATABASE: herba_scan_dashboard
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: user
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - proxy

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: herba-scan-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - proxy

volumes:
  mysql_data:

networks:
  proxy:
    external: true